keys = {
    4: "ebt excl. unusual items",
    5: "ebt excl. unusual items",
    7: "earnings from continuing operations",
    9: "basic eps",
    10: "gross profit",
    11: "total interest on borrowings",
    13: "interest expense",
    15: "net income_is",
    16: "net income to common incl extra items",
    17: "net interest income",
    21: "operating income",
    22: "operating income",
    24: "interest expense",
    25: "interest income",
    26: "non interest expense",
    27: "non interest income total",
    28: "revenue",
    29: "total revenues",
    31: "amortization of goodwill and intangible assets_is",
    32: "asset writedown",
    33: "asset writedown",
    34: "cost of goods sold",
    35: "property expenses",
    36: "policy acquisition /  underwriting costs",
    37: "cost of services provided",
    38: "currency exchange gains (loss)",
    39: "currency exchange gains (loss)",
    40: "earnings of discontinued operations",
    41: "depreciation & amortization_is",
    42: "extraordinary item & accounting change",
    43: "extraordinary item & accounting change",
    46: "(income) loss on equity invest.",
    47: "income (loss) on equity invest.",
    48: "income (loss) on equity invest.",
    49: "exploration / drilling costs",
    52: "finance div. revenues",
    55: "gain (loss) on sale of assets_is",
    56: "gain (loss) on sale of assets",
    57: "gain (loss) on sale of assets",
    60: "gain (loss) on sale of investments",
    61: "gain (loss) on sale of invest. & securities",
    62: "gain (loss) on sale of investments",
    63: "premiums and annuity revenues",
    64: "total interest and dividend income",
    65: "interest and investment income",
    66: "interest and investment income",
    67: "(income) loss on real estate property",
    68: "income (loss) on real estate property",
    70: "insurance division revenues",
    71: "impairment of oil gas & mineral properties",
    72: "in process r&d expenses",
    73: "insurance settlements",
    74: "insurance settlements",
    75: "income tax expense",
    76: "interest income on investments",
    77: "legal settlements",
    78: "legal settlements",
    79: "total mortgage banking activities",
    82: "interest expense",
    83: "minority interest_is",
    84: "non operating (income) expenses",
    85: "other non operating income (expenses)",
    86: "other non operating income (expenses)",
    87: "other unusual items",
    88: "other unusual items",
    89: "other operating expenses",
    90: "other revenues",
    91: "other revenues",
    92: "total other non interest expense",
    93: "total other non interest income",
    94: "policy benefits",
    95: "provision for bad debts",
    96: "pre-opening costs",
    97: "preferred dividend and other adjustments",
    99: "restructuring charges",
    100: "r&d expenses",
    101: "stock-based compensation (is)",
    102: "selling general & admin expenses",
    103: "selling general & admin expenses",
    104: "gain (loss) on sale of assets (rev)",
    105: "gain (loss) on sale of assets",
    106: "gain (loss) on sale of investment (rev)",
    107: "gain (loss) on sale of investments",
    108: "gain (loss) on sale of loans & receivables",
    109: "interest and dividend income",
    110: "interest and invest. income (rev)",
    111: "interest and investment income",
    112: "revenues",
    114: "allowance for borrowed funds used during construction",
    116: "allowance for equity funds used during construction",
    120: "asset management fee",
    125: "brokerage commission",
    126: "credit card fee",
    128: "commission and fees",
    135: "depreciation & amortization_is",
    139: "ebt incl. unusual items",
    142: "diluted eps excl extra items",
    152: "income (loss) on equity invest.",
    153: "salaries and other employee benefits",
    160: "federal deposit insurance",
    195: "(gain) loss on sale of loans",
    196: "gain (loss) on sale of loans",
    197: "amort. of goodwill & intang. assets",
    199: "underwriting & investment banking fee",
    205: "interest on deposits",
    209: "impairment of goodwill",
    212: "interest income on loans",
    215: "interest income on mortgage securities",
    237: "loan servicing revenue",
    241: "mortgage banking",
    244: "property management fee",
    247: "non-insurance activities expenses",
    248: "non-insurance activities revenues",
    250: "occupancy expense",
    255: "non operating income (expenses)",
    260: "other operating expenses",
    277: "provision for loan losses",
    278: "operations and maintenance",
    290: "trading and principal transactions",
    293: "tenant reimbursements",
    294: "reinsurance income or expense",
    298: "service charges on deposits",
    334: "rental revenues",
    336: "special dividends per share",
    337: "income from trading activities",
    338: "trust income",
    342: "weighted average diluted shares outstanding",
    356: "operating income",
    358: "other revenues",
    359: "provision for loan losses",
    360: "revenues before provison for loan losses",
    362: "credit card fee",
    363: "merger & restructuring charges",
    364: "total operating expenses",
    365: "total revenues",
    366: "compensation and benefits",
    367: "merger & restructuring charges",
    370: "net interest income",
    372: "other non operating income (expenses)",
    379: "net income to common excl. extra items",
    380: "total operating expenses",
    395: "amortization of goodwilland intangible assets_is",
    410: "revenues",
    411: "fuel & purchased power",
    1001: "total receivables",
    1002: "total cash and short term investments",
    1003: "net loans",
    1004: "net property plant and equipment",
    1005: "total preferred equity",
    1006: "total common equity",
    1007: "total assets",
    1008: "total current assets",
    1009: "total current liabilities",
    1010: "total deposits",
    1011: "total investments",
    1012: "total liabilities",
    1013: "total liabilities and equity",
    1015: "total real estate assets",
    1016: "accrued expenses",
    1017: "accrued expenses",
    1018: "accounts payable",
    1019: "accounts payable",
    1020: "accounts receivable",
    1021: "accounts receivable",
    1022: "comprehensive income and other",
    1024: "current portion of long-term debt",
    1025: "deferred charges long-term",
    1026: "deferred tax assets long-term",
    1027: "deferred tax liability non current",
    1028: "comprehensive income and other",
    1029: "finance division other current assets",
    1030: "finance division debt current",
    1031: "finance division other current liabilities",
    1032: "finance division loans and leases current",
    1033: "finance division loans and leases long-term",
    1034: "finance division other long-term assets",
    1035: "finance division debt non current",
    1036: "finance division other non current liabilities",
    1037: "insurance and annuity liabilities",
    1038: "long-term investments",
    1039: "investment in equity and preferred securities",
    1040: "other intangibles",
    1041: "other intangibles",
    1043: "inventory",
    1044: "investment securities",
    1045: "loans and lease receivables",
    1046: "short-term borrowings",
    1047: "short-term borrowings",
    1048: "notes receivable",
    1049: "long-term debt",
    1050: "loans receivable long-term",
    1051: "mortgage backed securities",
    1052: "minority interest_bs",
    1053: "minority interest_bs",
    1054: "long-term investments",
    1055: "other current assets",
    1056: "other current assets",
    1057: "other current liabilities",
    1058: "other current liabilities",
    1059: "total other investments",
    1060: "other long-term assets",
    1061: "other long-term assets",
    1062: "other non current liabilities",
    1063: "other non current liabilities",
    1064: "other receivables",
    1065: "preferred stock - others",
    1066: "preferred stock - others",
    1067: "reinsurance payable - (bs)",
    1068: "reinsurance recoverable - (is)",
    1069: "short term investments",
    1071: "trust preferred securities (bs)",
    1073: "unpaid claims",
    1074: "unearned revenue current",
    1075: "accumulated depreciation",
    1078: "accrued interest receivable",
    1080: "accrued interest payable",
    1081: "allowance for loan losses",
    1084: "additional paid in capital",
    1088: "accounts receivable long-term",
    1090: "current portion of capital lease obligations",
    1091: "interest bearing deposits",
    1092: "non-interest bearing deposits",
    1094: "current income taxes payable",
    1096: "cash and equivalents",
    1103: "common stock",
    1104: "restricted cash",
    1108: "assets of discontinued operations current",
    1112: "deferred charges long-term",
    1114: "distributions in excess of earnings",
    1115: "deferred policy acquisition costs - (bs)",
    1117: "deferred tax assets current",
    1118: "deferred tax assets long-term (collected)",
    1119: "deferred tax liability current",
    1120: "deferred tax liability non-current",
    1165: "federal home loan bank debt - long-term",
    1167: "investment in fhlb",
    1169: "gross property plant and equipment",
    1171: "goodwill",
    1175: "investment in debt securities",
    1176: "investment in debt and equity securities",
    1179: "inventory",
    1181: "investment in real estate",
    1183: "capital leases",
    1184: "land held for development or sale",
    1185: "loans held for sale",
    1188: "gross loans",
    1189: "short-term borrowings",
    1190: "notes receivable (collected)",
    1191: "loans receivable long-term",
    1192: "assets of discontinued operations long-term",
    1193: "long-term debt",
    1194: "long-term investments",
    1197: "mortgage loans",
    1200: "net nuclear fuel",
    1202: "other current liabilities",
    1205: "other non current liabilities",
    1206: "other receivables",
    1207: "other real estate owned and foreclosed",
    1208: "other adjustments to gross loans",
    1211: "policy loans",
    1212: "prepaid expenses",
    1213: "pension & other post retirement benefits",
    1214: "preferred stock convertible",
    1216: "preferred stock non redeemable",
    1217: "preferred stock redeemable",
    1220: "regulatory assets",
    1222: "retained earnings",
    1223: "real estate owned",
    1230: "separate account assets",
    1231: "separate account liability",
    1234: "securities borrowed",
    1235: "cash & securities segregated",
    1236: "securities owned",
    1240: "securities purchased under agreements to resell",
    1242: "short term investments",
    1244: "trading asset securities",
    1245: "institutional deposits",
    1248: "treasury stock",
    1252: "unearned premiums",
    1255: "current unearned revenue",
    1256: "unearned revenue non current",
    1268: "other liabilities",
    1275: "total equity",
    1276: "total liabilities",
    1277: "deposits",
    1297: "current portion of long-term debt",
    1310: "tangible book value",
    1312: "total minority interest",
    2002: "depreciation, depletion & amortization",
    2004: "cash from financing",
    2005: "cash from investing",
    2006: "cash from operations",
    2010: "memo: change in net working capital",
    2014: "amortization of deferred charges",
    2015: "amortization of deferred charges",
    2016: "amortization of goodwill and intangible assets",
    2017: "change in accounts payable",
    2018: "change in accounts receivable",
    2019: "asset writedown & restructuring costs",
    2020: "total asset writedown",
    2021: "capital expenditure",
    2022: "common & preferred stock dividends paid",
    2026: "(gain) loss from sale of asset",
    2027: "investment in marketable and equity securities",
    2028: "investment in marketable and equity securities",
    2029: "sale (purchase) of intangible assets",
    2030: "purchase / sale of intangible assets",
    2031: "impairment of oil, gas & mineral properties",
    2032: "net (increase) decrease in loans originated / sold - investing",
    2033: "net (increase) decrease in loans originated / sold - operating",
    2040: "sale (purchase) of real estate properties",
    2041: "special dividend paid",
    2042: "sale of property, plant, and equipment",
    2045: "change in other net operating assets",
    2046: "other operating activities",
    2047: "other operating activities",
    2048: "other investing activities",
    2049: "other financing activities",
    2050: "other financing activities",
    2051: "other investing activities",
    2055: "cash and cash equivalents, beginning of period",
    2056: "cash and cash equivalents, end of period",
    2057: "cash acquisitions",
    2059: "amort. of deferred policy acq. costs",
    2060: "changes in accrued interest payable",
    2061: "changes in accrued interest receivable",
    2065: "annuity payments",
    2066: "change in accounts payable",
    2067: "change in accounts receivable",
    2068: "annuity receipts",
    2074: "common dividends paid",
    2077: "divestitures",
    2078: "net increase (decrease) in deposit accounts",
    2079: "deferred charges",
    2081: "net cash from discontinued operations",
    2082: "deferred policy acquisition costs",
    2084: "change in deferred taxes",
    2086: "(income) loss on equity investments",
    2089: "(gain) loss on sale of asset",
    2090: "(gain) loss on sale of investments",
    2091: "gain (loss) on sale of loans & receivables",
    2093: "net change in cash",
    2095: "change in insurance reserves / liabilities",
    2099: "change in inventories",
    2101: "change in income taxes",
    2103: "net (increase) decrease in loans originated / sold operating -",
    2107: "minority interest in earnings",
    2108: "contributions to nuclear decommissioning trust",
    2109: "nuclear fuel expenditures",
    2111: "provision and write-off of bad debts",
    2112: "provision for credit losses",
    2114: "capital expenditure",
    2116: "preferred dividends paid",
    2120: "restructuring activities",
    2121: "reinsurance payable",
    2122: "reinsurance recoverable",
    2123: "sale (purchase) of real estate properties",
    2124: "acquisition of real estate assets",
    2125: "sale of real estate assets",
    2126: "sale / securitization of accounts receivable",
    2127: "stock-based compensation",
    2130: "sale of property, plant and equipment",
    2134: "change in trading asset securities",
    2135: "tax benefit from stock options",
    2139: "change in unearned revenues",
    2140: "change in other net operating assets",
    2144: "foreign exchange rate adjustments",
    2149: "miscellaneous cash flow adjustments",
    2150: "net income_cf",
    2159: "issuance of common stock",
    2160: "total depreciation & amortization",
    2161: "total debt issued",
    2162: "total debt issued",
    2163: "total debt repaid",
    2164: "repurchase of common stock",
    2165: "repurchase of common stock",
    2166: "total debt repaid",
    2169: "issuance of common stock",
    2170: "repurchase of preferred stock",
    2171: "depreciation & amortization",
    2172: "repurchase of preferred stock",
    2174: "issuance of preferred stock",
    2181: "issuance of preferred stock",
    2182: "amortization of goodwill and intangible assets",
    2185: "total depreciation, depletion & amortization",
    3023: "buildings",
    3028: "cash interest paid",
    3053: "cash taxes paid",
    3058: "dividends per share",
    3063: "equity method investments",
    3074: "ffo",
    3085: "full time employees",
    3098: "land",
    3168: "r&d expense",
    3195: "same store sales growth %",
    3217: "weighted average basic shares outstanding",
    4001: "receivables turnover",
    4020: "book value/share",
    4030: "current ratio",
    4034: "total debt / equity",
    4035: "avg. days outstanding inventory",
    4037: "dividend payout %",
    4038: "dividend yield %",
    4042: "avg. days sales outstanding",
    4047: "ebitda margin %",
    4051: "ebitda",
    4053: "ebit margin %",
    4066: "fixed assets turnover",
    4074: "gross profit margin %",
    4082: "inventory turnover",
    4094: "net income margin %",
    4117: "ebt excl. non-recurring items margin %",
    4121: "quick ratio",
    4128: "return on equity %",
    4156: "tangible book value/share",
    4173: "total debt",
    4178: "return on assets %",
    4181: "income from continuing operations margin %",
    4182: "net avail. for common margin %",
    4183: "avg. days payable outstanding",
    4184: "avg. cash conversion cycle",
    4185: "op cash flow to current liab",
    4188: "total liabilities / total assets",
    4189: "ebit / interest expense",
    4190: "ebitda / interest expense",
    4191: "(ebitda - capex) / interest expense",
    4192: "total debt / ebitda",
    4193: "net debt / ebitda",
    4278: "ebt margin %",
    4279: "nonperforming loans / total loans %",
    4280: "nonperforming loans / total assets %",
    4281: "nonperforming assets / total assets %",
    4282: "allowance for credit losses / net charge-offs %",
    4283: "allowance for credit losses / nonperforming loans %",
    4284: "allowance for credit losses / total loans %",
    4285: "net charge-offs / total average loans %",
    4286: "provision for loan losses / net charge-offs %",
    4287: "total average common equity / total average assets %",
    4288: "total equity + allowance for loan losses / total loans %",
    4290: "gross loans / total deposits %",
    4292: "tier 1 capital ratio %",
    4293: "total capital ratio %",
    4364: "net debt",
    4375: "sg&a margin %",
    4376: "effective tax rate %",
    4377: "payout ratio %",
    4419: "ebita margin %",
    4420: "normalized net income margin %",
    4436: "levered free cash flow margin %",
    4437: "unlevered free cash flow margin %",
    21561: "selling and marketing expense",
    21562: "general and administrative expense",
    21674: "ebitdar",
    22985: "maintenance capex",
    23314: "net debt / (ebitda - capex)",
    23315: "annualized distributions per unit",
    24138: "ffo payout ratio %",
    24153: "total shares out. on filing date",
    24216: "construction in progress",
    33320: "return on common equity %",
    33384: "distributable cash per share (diluted)",
    34819: "core tier 1 capital ratio %",
    34823: "tier 2 capital ratio %",
    34827: "equity tier 1 capital ratio %",
    34838: "interest income / average assets %",
    34839: "interest expense / average assets %",
    34840: "net interest income / average assets %",
    34843: "earning assets / interest bearing liabilities %",
    34860: "nonperforming assets / equity %",
    41571: "net income to company",
    43903: "ffo interest coverage",
    43904: "ffo to total debt (x)",
    43905: "return on capital %",
    43907: "total debt / capital",
    43913: "working capital turnover",
    43917: "asset turnover",
    43923: "cash flow per share"
}

statements = [
    {
        'statement': 'income_statement',
        'keys': {
            'Revenues': 28,
            'Total Revenues': 112,
            'Total Revenues YoY': '',
            'Cost of Goods Sold': 34,
            'Gross Profit': 10,
            'Gross Profit YoY': '',
            '% Gross Margins': 4074,
            'Selling General & Admin Expenses': 102,
            'R&D Expenses': 3168,
            'Total Operating Expenses': 380,
            'Operating Income': 21,
            'Operating Income YoY': '',
            '% Operating Margins': 4053,
            'Interest Expense': 82,
            'Interest And Investment Income': 65,
            'Currency Exchange Gains (Loss)': 38,
            'Other Non Operating Income (Expenses)': 85,
            'EBT Excl. Unusual Items': 4,
            'Gain (Loss) On Sale Of Investments': 62,
            'Gain (Loss) On Sale Of Assets': 104,
            'Asset Writedown': 2019,
            'In Process R&D Expenses': 72,
            'Legal Settlements': 77,
            'Other Unusual Items': 87,
            'EBT Incl. Unusual Items': 139,
            'Income Tax Expense': 75,
            'Earnings From Continuing Operations': 7,
            'Earnings Of Discontinued Operations': 40,
            'Net Income to Company': 41571,
            'Net Income': 15,
            'Net Income to Common Incl Extra Items': 16,
            '% Net Income to Common Incl Extra Items Margins': 4094,
            'Net Income to Common Excl. Extra Items': 379,
            '% Net Income to Common Excl. Extra Items Margins': 4181,
            'Diluted EPS Excl Extra Items': 142,
            'Diluted EPS Excl Extra Items YoY': '',
            'Weighted Average Diluted Shares Outstanding': 342,
            'Weighted Average Diluted Shares Outstanding YoY': '',
            'Weighted Average Basic Shares Outstanding': 3217,
            'Weighted Average Basic Shares Outstanding YoY': '',
            'Basic EPS': 9,
            'EBITDA': 4051,
            'EBITDA YoY': '',
            'EBITDAR': 21674,
            'R&D Expense': 3168,
            'Selling and Marketing Expense': 21561,
            'General and Administrative Expense': 21562,
            'Effective Tax Rate %': 4376
        }
    },
    {
        'statement': 'cashflow_statement',
        'keys': {
            'Net Income': 15,
            'Depreciation & Amortization': 2171,
            'Amortization of Goodwill and Intangible Assets': 2182,
            'Total Depreciation & Amortization': 2160,
            '(Gain) Loss From Sale Of Asset': 2026,
            '(Gain) Loss on Sale of Investments': 2090,
            'Asset Writedown & Restructuring Costs': 2019,
            'Stock-Based Compensation': 2127,
            'Tax Benefit from Stock Options': 2135,
            'Net Cash From Discontinued Operations': 2081,
            'Other Operating Activities': 2047,
            'Change In Accounts Receivable': 2018,
            'Change In Inventories': 2140,
            'Change In Accounts Payable': 2017,
            'Change in Unearned Revenues': 2139,
            'Change In Income Taxes': 2101,
            'Change in Other Net Operating Assets': 2045,
            'Cash from Operations': 2006,
            'Change in Net Working Capital': 2010,
            'Capital Expenditure': 2021,
            'Sale of Property, Plant, and Equipment': 2042,
            'Cash Acquisitions': 2057,
            'Divestitures': 2077,
            'Sale (Purchase) of Intangible assets': 2029,
            'Investment in Marketable and Equity Securities': 2027,
            'Other Investing Activities': 2051,
            'Cash from Investing': 2005,
            'Total Debt Issued': 2161,
            'Total Debt Repaid': 2166,
            'Issuance of Common Stock': 2169,
            'Repurchase of Common Stock': 2164,
            'Other Financing Activities': 2050,
            'Cash from Financing': 2004,
            'Foreign Exchange Rate Adjustments': 2144,
            'Net Change in Cash': 2093,
            'Free Cash Flow': '',
            'Free Cash Flow YoY': '',
            '% Free Cash Flow Margins': '',
            'Cash and Cash Equivalents, Beginning of Period': 2055,
            'Cash and Cash Equivalents, End of Period': 2056,
            'Cash Interest Paid': 3028,
            'Cash Taxes Paid': 3053,
            'Cash Flow per Share': 43923
        }
    },
    {
        'statement': 'balancesheet_statement',
        'keys': {
            'Cash And Equivalents': 1096,
            'Short Term Investments ': 1069,
            'Total Cash And Short Term Investments ': 1002,
            'Accounts Receivable': 1021,
            'Other Receivables ': 1206,
            'Notes Receivable': 1048,
            'Total Receivables': 1001,
            'Inventory ': 1043,
            'Prepaid Expenses': 1212,
            'Deferred Tax Assets Current': 1117,
            'Restricted Cash': 1104,
            'Other Current Assets ': 1055,
            'Total Current Assets ': 1008,
            'Gross Property Plant And Equipment': 1169,
            'Accumulated Depreciation': 1075,
            'Net Property Plant And Equipment ': 1004,
            'Long-term Investments ': 1054,
            'Goodwill': 1171,
            'Other Intangibles': 1040,
            'Loans Receivable Long-Term ': 1050,
            'Deferred Tax Assets Long-Term ': 1026,
            'Other Long-Term Assets ': 1060,
            'Total Assets ': 1007,
            'Accounts Payable': 1018,
            'Accrued Expenses': 1016,
            'Short-term Borrowings ': 1046,
            'Current Portion of Long-Term Debt': 1297,
            'Current Portion of Capital Lease Obligations': 1090,
            'Current Income Taxes Payable ': 1094,
            'Unearned Revenue Current ': 1074,
            'Other Current Liabilities ': 1057,
            'Total Current Liabilities ': 1009,
            'Long-Term Debt ': 1049,
            'Capital Leases': 1183,
            'Unearned Revenue Non Current': 1256,
            'Deferred Tax Liability Non Current ': 1027,
            'Other Non Current Liabilities ': 1062,
            'Total Liabilities ': 1276,
            'Preferred Stock Convertible ': 1214,
            'Preferred Stock - Others ': 1065,
            'Total Preferred Equity ': 1005,
            'Common Stock': 1103,
            'Additional Paid In Capital': 1084,
            'Retained Earnings': 1222,
            'Comprehensive Income and Other ': 1028,
            'Total Common Equity ': 1006,
            'Total Equity ': 1275,
            'Total Liabilities And Equity ': 1013,
            'Total Shares Out. on Filing Date ': 24153,
            'Book Value/Share ': 4020,
            'Tangible Book Value': 1310,
            'Tangible Book Value/Share ': 4156,
            'Total Debt ': 4173,
            'Net Debt': 4364,
            'Equity Method Investments ': 3063,
            'Land ': 3098,
            'Buildings ': 3023,
            'Construction In Progress ': 24216,
            'Full Time Employees': 3085
        }
    },
]