# Auto-generated column configuration using TIKR /tf metadata.
statements = [{'statement': 'income_statement',
               'keys': {'Revenues': 'Total Revenues',
                        'Total Revenues': 'Revenues',
                        'Total Revenues YoY': '',
                        'Cost of Goods Sold': 'Cost of Goods Sold',
                        'Gross Profit': 'Gross Profit',
                        'Gross Profit YoY': '',
                        '% Gross Margins': 'Gross Profit Margin %',
                        'Selling General & Admin Expenses': 'Selling General & Admin Expenses',
                        'R&D Expenses': 'R&D Expense',
                        'Total Operating Expenses': 'Total Operating Expenses',
                        'Operating Income': 'Operating Income',
                        'Operating Income YoY': '',
                        '% Operating Margins': 'EBIT Margin %',
                        'Interest Expense': 'Interest Expense',
                        'Interest And Investment Income': 'Interest And Investment Income',
                        'Currency Exchange Gains (Loss)': 'Currency Exchange Gains (Loss)',
                        'Other Non Operating Income (Expenses)': 'Other Non Operating Income (Expenses)',
                        'EBT Excl. Unusual Items': 'EBT Excl. Unusual Items',
                        'Gain (Loss) On Sale Of Investments': 'Gain (Loss) On Sale Of Investments',
                        'Gain (Loss) On Sale Of Assets': 'Gain (Loss) on Sale of Assets (Rev)',
                        'Asset Writedown': 'Asset Writedown & Restructuring Costs',
                        'In Process R&D Expenses': 'In Process R&D Expenses',
                        'Legal Settlements': 'Legal Settlements',
                        'Other Unusual Items': 'Other Unusual Items',
                        'EBT Incl. Unusual Items': 'EBT Incl. Unusual Items',
                        'Income Tax Expense': 'Income Tax Expense',
                        'Earnings From Continuing Operations': 'Earnings From Continuing Operations',
                        'Earnings Of Discontinued Operations': 'Earnings Of Discontinued Operations',
                        'Net Income to Company': 'Net Income to Company',
                        'Net Income': 'Net Income',
                        'Net Income to Common Incl Extra Items': 'Net Income to Common Incl Extra Items',
                        '% Net Income to Common Incl Extra Items Margins': 'Net Income Margin %',
                        'Net Income to Common Excl. Extra Items': 'Net Income to Common Excl. Extra Items',
                        '% Net Income to Common Excl. Extra Items Margins': ('Income From Continuing Operations '
                                                                             'Margin %'),
                        'Diluted EPS Excl Extra Items': 'Diluted EPS Excl Extra Items',
                        'Diluted EPS Excl Extra Items YoY': '',
                        'Weighted Average Diluted Shares Outstanding': ('Weighted Average Diluted Shares '
                                                                        'Outstanding'),
                        'Weighted Average Diluted Shares Outstanding YoY': '',
                        'Weighted Average Basic Shares Outstanding': 'Weighted Average Basic Shares Outstanding',
                        'Weighted Average Basic Shares Outstanding YoY': '',
                        'Basic EPS': 'Basic EPS',
                        'EBITDA': 'EBITDA',
                        'EBITDA YoY': '',
                        'EBITDAR': 'EBITDAR',
                        'R&D Expense': 'R&D Expense',
                        'Selling and Marketing Expense': 'Selling and Marketing Expense',
                        'General and Administrative Expense': 'General and Administrative Expense',
                        'Effective Tax Rate %': 'Effective Tax Rate %'}},
              {'statement': 'cashflow_statement',
               'keys': {'Net Income': 'Net Income',
                        'Depreciation & Amortization': 'Depreciation & Amortization',
                        'Amortization of Goodwill and Intangible Assets': 'Amortization of Goodwill and '
                                                                          'Intangible Assets',
                        'Total Depreciation & Amortization': 'Total Depreciation & Amortization',
                        '(Gain) Loss From Sale Of Asset': '(Gain) Loss From Sale Of Asset',
                        '(Gain) Loss on Sale of Investments': '(Gain) Loss on Sale of Investments',
                        'Asset Writedown & Restructuring Costs': 'Asset Writedown & Restructuring Costs',
                        'Stock-Based Compensation': 'Stock-Based Compensation',
                        'Tax Benefit from Stock Options': 'Tax Benefit from Stock Options',
                        'Net Cash From Discontinued Operations': 'Net Cash From Discontinued Operations',
                        'Other Operating Activities': 'Other Operating Activities',
                        'Change In Accounts Receivable': 'Change In Accounts Receivable',
                        'Change In Inventories': 'Change In Inventories',
                        'Change In Accounts Payable': 'Change In Accounts Payable',
                        'Change in Unearned Revenues': 'Change in Unearned Revenues',
                        'Change In Income Taxes': 'Change In Income Taxes',
                        'Change in Other Net Operating Assets': 'Change in Other Net Operating Assets',
                        'Cash from Operations': 'Cash from Operations',
                        'Change in Net Working Capital': 'Memo: Change in Net Working Capital',
                        'Capital Expenditure': 'Capital Expenditure',
                        'Sale of Property, Plant, and Equipment': 'Sale of Property, Plant, and Equipment',
                        'Cash Acquisitions': 'Cash Acquisitions',
                        'Divestitures': 'Divestitures',
                        'Sale (Purchase) of Intangible assets': 'Sale (Purchase) of Intangible assets',
                        'Investment in Marketable and Equity Securities': 'Investment in Marketable and Equity '
                                                                          'Securities',
                        'Other Investing Activities': 'Other Investing Activities',
                        'Cash from Investing': 'Cash from Investing',
                        'Total Debt Issued': 'Total Debt Issued',
                        'Total Debt Repaid': 'Total Debt Repaid',
                        'Issuance of Common Stock': 'Issuance of Common Stock',
                        'Repurchase of Common Stock': 'Repurchase of Common Stock',
                        'Other Financing Activities': 'Other Financing Activities',
                        'Cash from Financing': 'Cash from Financing',
                        'Foreign Exchange Rate Adjustments': 'Foreign Exchange Rate Adjustments',
                        'Net Change in Cash': 'Net Change in Cash',
                        'Free Cash Flow': '',
                        'Free Cash Flow YoY': '',
                        '% Free Cash Flow Margins': '',
                        'Cash and Cash Equivalents, Beginning of Period': 'Cash and Cash Equivalents, Beginning '
                                                                          'of Period',
                        'Cash and Cash Equivalents, End of Period': 'Cash and Cash Equivalents, End of Period',
                        'Cash Interest Paid': 'Cash Interest Paid',
                        'Cash Taxes Paid': 'Cash Taxes Paid',
                        'Cash Flow per Share': 'Cash Flow per Share'}},
              {'statement': 'balancesheet_statement',
               'keys': {'Cash And Equivalents': 'Cash And Equivalents',
                        'Short Term Investments ': 'Short Term Investments',
                        'Total Cash And Short Term Investments ': 'Total Cash And Short Term Investments',
                        'Accounts Receivable': 'Accounts Receivable',
                        'Other Receivables ': 'Other Receivables',
                        'Notes Receivable': 'Notes Receivable',
                        'Total Receivables': 'Total Receivables',
                        'Inventory ': 'Inventory',
                        'Prepaid Expenses': 'Prepaid Expenses',
                        'Deferred Tax Assets Current': 'Deferred Tax Assets Current',
                        'Restricted Cash': 'Restricted Cash',
                        'Other Current Assets ': 'Other Current Assets',
                        'Total Current Assets ': 'Total Current Assets',
                        'Gross Property Plant And Equipment': 'Gross Property Plant And Equipment',
                        'Accumulated Depreciation': 'Accumulated Depreciation',
                        'Net Property Plant And Equipment ': 'Net Property Plant And Equipment',
                        'Long-term Investments ': 'Long-term Investments',
                        'Goodwill': 'Goodwill',
                        'Other Intangibles': 'Other Intangibles',
                        'Loans Receivable Long-Term ': 'Loans Receivable Long-Term',
                        'Deferred Tax Assets Long-Term ': 'Deferred Tax Assets Long-Term',
                        'Other Long-Term Assets ': 'Other Long-Term Assets',
                        'Total Assets ': 'Total Assets',
                        'Accounts Payable': 'Accounts Payable',
                        'Accrued Expenses': 'Accrued Expenses',
                        'Short-term Borrowings ': 'Short-term Borrowings',
                        'Current Portion of Long-Term Debt': 'Current Portion of Long-Term Debt',
                        'Current Portion of Capital Lease Obligations': 'Current Portion of Capital Lease '
                                                                        'Obligations',
                        'Current Income Taxes Payable ': 'Current Income Taxes Payable',
                        'Unearned Revenue Current ': 'Unearned Revenue Current',
                        'Other Current Liabilities ': 'Other Current Liabilities',
                        'Total Current Liabilities ': 'Total Current Liabilities',
                        'Long-Term Debt ': 'Long-Term Debt',
                        'Capital Leases': 'Capital Leases',
                        'Unearned Revenue Non Current': 'Unearned Revenue Non Current',
                        'Deferred Tax Liability Non Current ': 'Deferred Tax Liability Non Current',
                        'Other Non Current Liabilities ': 'Other Non Current Liabilities',
                        'Total Liabilities ': 'Total Liabilities',
                        'Preferred Stock Convertible ': 'Preferred Stock Convertible',
                        'Preferred Stock - Others ': 'Preferred Stock - Others',
                        'Total Preferred Equity ': 'Total Preferred Equity',
                        'Common Stock': 'Common Stock',
                        'Additional Paid In Capital': 'Additional Paid In Capital',
                        'Retained Earnings': 'Retained Earnings',
                        'Comprehensive Income and Other ': 'Comprehensive Income and Other',
                        'Total Common Equity ': 'Total Common Equity',
                        'Total Equity ': 'Total Equity',
                        'Total Liabilities And Equity ': 'Total Liabilities And Equity',
                        'Total Shares Out. on Filing Date ': 'Total Shares Out. on Filing Date',
                        'Book Value/Share ': 'Book Value / Share',
                        'Tangible Book Value': 'Tangible Book Value',
                        'Tangible Book Value/Share ': 'Tangible Book Value / Share',
                        'Total Debt ': 'Total Debt',
                        'Net Debt': 'Net Debt',
                        'Equity Method Investments ': 'Equity Method Investments',
                        'Land ': 'Land',
                        'Buildings ': 'Buildings',
                        'Construction In Progress ': 'Construction In Progress',
                        'Full Time Employees': 'Full Time Employees'}}]
